services:
  api-gateway:
    container_name: api-gateway
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=development
      # 在这里使用环境变量把路由地址覆写为 Docker 内部的服务名！
      - ROUTES_USER_PLATFORM=http://user-http:8081
      - ROUTES_USER_PLATFORM_GRPC=user-grpc:9091
      - ROUTES_GO_NOTE=http://go-note:8080
      # 如果启用了限流器，同样覆写 Redis 的地址为公网或 infra 网络里的名字
      - REDIS_ADDR=global-redis:6379
      - OTEL_JAEGER_ENDPOINT=global-jaeger:4318
    networks:
      - go-net
    restart: unless-stopped

networks:
  go-net:
    name: go-net
    external: true
