server:
  port: "8000"
  cors_origins:
    - "http://localhost:3000"
    - "http://127.0.0.1:3000"
    - "http://localhost:5173"
    - "http://127.0.0.1:5173"
    - "http://localhost:5174"
    - "http://127.0.0.1:5174"

routes:
  user_platform_http: "http://localhost:8081"
  user_platform_grpc: "localhost:9091"
  go_note: "http://localhost:8080"
  go_chat: "http://localhost:8083"

jwt:
  secret: "user_platform_secret_key" # 和 user-platform 对齐的解析秘钥

redis:
  addr: "localhost:6379"
  password: "123456"
  db: 0

otel:
  jaeger_endpoint: "localhost:4318"
  service_name: "api-gateway"
